name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 14.x
    - name: Install dependencies
      run: yarn install
    - name: Build
      run: yarn run build
    - name: Test
      run: yarn run test
    - name: Build standalone
      run: npm run build-standalone-prod
    - name: Upload standalone artifact
      uses: actions/upload-artifact@v2
      with:
        name: standalone
        path: dist/standalone.html
